window.package("zetaret.global.packages.clockwork.graphics").internal(
function GraphicCommand() {
	var o = this,
		a = arguments;
	o.command = 0;
	o.super(a, true);
	var m = {};
	m.toCommandData = function() {
		return null;
	};
	o.superize(a, m, true, true);
	return o;
});
ProtoSS.staticProps(zetaret.global.packages.clockwork.graphics.GraphicCommand, {
TYPES: {
NO_OP: 0,
MOVE_TO: 1,
LINE_TO: 2,
CURVE_TO: 3,
TRANSFORM: 4,
SET_TRANSFORM: 5,
CUBIC_CURVE_TO: 6,
PATH: 7,
CLOSE_PATH: 8,
DASH: 9,
CLIP: 10,
RESET_TRANSFORM: 11,
TRANSLATE: 12,
SCALE: 13,
ROTATE: 14,
SKEW: 15,
FILL_RECT: 20,
STROKE_RECT: 21,
CLEAR_RECT: 22,
RECT: 23,
ELLIPSE: 24,
ARC: 25,
ARC_TO: 26,
BEGIN_FILL: 30,
END_FILL: 31,
STROKE: 32,
BITMAP_FILL: 33,
GRADIENT_FILL: 34,
RADIAL_GRADIENT_FILL: 35,
SOLID_FILL: 36,
TEXT: 37,
LINE: 38,
SHADOW: 39,
FILL_TEXT: 40,
STROKE_TEXT: 41,
IMAGE: 42,
IMAGE_RECT: 43,
COMPOSITE: 44,
LINEAR_GRADIENT: 45,
RADIAL_GRADIENT: 46,
PATTERN: 47,
BLEND: 50,
FILTER: 51,
ALPHA: 52,
STYLE: 53,
CLEAR_STYLE: 60,
CLEAR_SHADOW: 61,
CLEAR_TEXT: 62,
CLEAR_STROKE: 63,
CLEAR_COLOR: 64,
SAVE: 70,
RESTORE: 71,
IMAGE_DATA: 80,
IMAGE_DATA_FILTER: 81,
SHADER: 82,
SET_COLOR_TRANSFORM: 83,
RESET_COLOR_TRANSFORM: 84,
RESET_COLOR: 85,
RESET_STROKE: 86,
RESET_TEXT: 87,
RESET_SHADOW: 88
}
});